Bookmarks/Controllers/BookmarkController.cs
using Bookmarks.Data.Handlers;
using Bookmarks.Models;
using Bookmarks.UseCases.Commands;
using Bookmarks.UseCases.Queries;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using OpenCqs;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Security.Claims;

namespace Bookmarks.Controllers
{
    [Authorize]
    public class BookmarkController : Controller
    {
        private readonly ILogger<BookmarkController> logger;
        readonly ICommandHandler<AddBookmarkCommand, CommandResult> addBookmark;
        readonly IQueryHandler<GetGroupsForSelectQuery, IEnumerable<BookmarkListModel.GroupSelect>> getGroupsForSelect;
        readonly ICommandHandler<AddGroupCommand, CommandResult> addGroup;
        readonly IQueryHandler<GetGroupsQuery, IEnumerable<GroupModel>> getGroups;
        readonly IQueryHandler<GetGroupByIdQuery, GroupModel> getGroupById;
        readonly ICommandHandler<UpdateGroupCommand, CommandResult> updateGroup;
        readonly IQueryHandler<GetBookmarksQuery, IEnumerable<BookmarkModel>> getBookmarks;
        readonly ICommandHandler<SetGroupCommand, CommandResult> setGroup;
        readonly IQueryHandler<GetBookmarkQuery, BookmarkModel> getBookmark;
        readonly ICommandHandler<UpdateBookmarkCommand, CommandResult> updateBookmark;
        readonly ICommandHandler<DeleteGroupCommand, CommandResult> deleteGroup;
        readonly ICommandHandler<DeleteBookmarkCommand, CommandResult> deleteBookmark;

        public BookmarkController(ILogger<BookmarkController> logger
            , IQueryHandler<GetGroupsForSelectQuery, IEnumerable<BookmarkListModel.GroupSelect>> getGroupsForSelect
            , IQueryHandler<GetGroupsQuery, IEnumerable<GroupModel>> getGroups
            , IQueryHandler<GetGroupByIdQuery, GroupModel> getGroupById
            , IQueryHandler<GetBookmarksQuery, IEnumerable<BookmarkModel>> getBookmarks
            , IQueryHandler<GetBookmarkQuery, BookmarkModel> getBookmark
            , ICommandHandler<AddBookmarkCommand, CommandResult> addBookmark
            , ICommandHandler<AddGroupCommand, CommandResult> addGroup
            , ICommandHandler<UpdateGroupCommand, CommandResult> updateGroup
            , ICommandHandler<SetGroupCommand, CommandResult> setGroup
            , ICommandHandler<UpdateBookmarkCommand, CommandResult> updateBookmark
            , ICommandHandler<DeleteBookmarkCommand, CommandResult> deleteBookmark
            , ICommandHandler<DeleteGroupCommand, CommandResult> deleteGroup)
        {
            this.deleteBookmark = deleteBookmark ?? throw new ArgumentNullException(nameof(deleteBookmark), $"{nameof(deleteBookmark)} is null.");
            this.deleteGroup = deleteGroup ?? throw new ArgumentNullException(nameof(deleteGroup), $"{nameof(deleteGroup)} is null.");
            this.updateBookmark = updateBookmark ?? throw new ArgumentNullException(nameof(updateBookmark), $"{nameof(updateBookmark)} is null.");
            this.getBookmark = getBookmark ?? throw new ArgumentNullException(nameof(getBookmark), $"{nameof(getBookmark)} is null.");
            this.setGroup = setGroup ?? throw new ArgumentNullException(nameof(setGroup), $"{nameof(setGroup)} is null.");
            this.getBookmarks = getBookmarks ?? throw new ArgumentNullException(nameof(getBookmarks), $"{nameof(getBookmarks)} is null.");
            this.updateGroup = updateGroup ?? throw new ArgumentNullException(nameof(updateGroup), $"{nameof(updateGroup)} is null.");
            this.getGroupById = getGroupById ?? throw new ArgumentNullException(nameof(getGroupById), $"{nameof(getGroupById)} is null.");
            this.getGroups = getGroups ?? throw new ArgumentNullException(nameof(getGroups), $"{nameof(getGroups)} is null.");
            this.addGroup = addGroup ?? throw new ArgumentNullException(nameof(addGroup), $"{nameof(addGroup)} is null.");
            this.getGroupsForSelect = getGroupsForSelect ?? throw new ArgumentNullException(nameof(getGroupsForSelect), $"{nameof(getGroupsForSelect)} is null.");
            this.addBookmark = addBookmark ?? throw new ArgumentNullException(nameof(addBookmark), $"{nameof(addBookmark)} is null.");
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public IActionResult Index(string search)
        {
            var filter = new BookmarkListModel.BookmarkFilter(search);
            this.TempData["Title"] = "Bookmarks";
            return this.View(new BookmarkListModel(this.getBookmarks, this.getGroupsForSelect, filter));
        }

        [HttpPost]
        public IActionResult Index(BookmarkListModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
                var result = this.addBookmark.Handle(new AddBookmarkCommand(model.Title, model.Url, model.Description, model.GroupId, userId));
                if (result.IsSuccess)
                {
                    return this.RedirectToAction(nameof(Index));
                }

                this.ModelState.AddModelError(nameof(model.Url), result.Exception.Message);
            }

            return this.View(new BookmarkListModel(this.getBookmarks, this.getGroupsForSelect));
        }

        public IActionResult Edit(Guid id)
        {
            var model = this.getBookmark.Handle(new GetBookmarkQuery(id));
            return this.View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(BookmarkModel model)
        {
            if (this.ModelState.IsValid)
            {
                var result = this.updateBookmark.Handle(new UpdateBookmarkCommand(model.Id, model.Title, model.Url, model.Description));
                if (result.IsSuccess)
                {
                    return this.View();
                }

                this.ModelState.AddModelError(nameof(model.Url), result.Exception.Message);
            }

            return this.View(model);
        }

        [HttpPost/*, ValidateAntiForgeryToken*/]
        public IActionResult Delete(Guid id)
        {
            this.deleteBookmark.Handle(new DeleteBookmarkCommand(id));
            return this.Ok();
        }

        public IActionResult Groups(Guid id)
        {
            var model = this.getGroupById.Handle(new GetGroupByIdQuery(id));
            model.Groups = this.getGroups.Handle(new GetGroupsQuery());
            return this.View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Groups(GroupModel model)
        {
            var groups = this.getGroups.Handle(new GetGroupsQuery());
            if (this.ModelState.IsValid)
            {
                var message = string.Empty;
                if (model.Id != Guid.Empty)
                {
                    var result = this.updateGroup.Handle(new UpdateGroupCommand(model.Id, model.Name, model.Description));
                    if (result.IsSuccess)
                    {
                        model = new GroupModel { Groups = groups };
                        return this.View(model);
                    }

                    message = result.Exception.Message;
                }
                else
                {
                    var userId = this.User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
                    var result = this.addGroup.Handle(new AddGroupCommand(model.Name, model.Description, userId));
                    if (result.IsSuccess)
                    {
                        model = new GroupModel { Groups = groups };
                        return this.View(model);
                    }

                    message = result.Exception.Message;
                }

                this.ModelState.AddModelError(nameof(model.Name), message);
            }

            model.Groups = groups;
            return this.View(model);
        }

        [HttpPost/*, ValidateAntiForgeryToken*/]
        public IActionResult DeleteGroup(Guid id)
        {
            this.deleteGroup.Handle(new DeleteGroupCommand(id));
            return this.RedirectToAction(nameof(Groups));
        }

        [HttpPost]
        public IActionResult SetGroup(Guid id, Guid groupId)
        {
            var command = new SetGroupCommand(id, groupId);
            var result = this.setGroup.Handle(command);
            return result.IsSuccess ? this.Ok() : throw new Exception("Booom!");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, });
        }
    }
}

Bookmarks/Views/Bookmark/Edit.cshtml
@using Microsoft.AspNetCore.Html;
@using System.IO;
@using System.Web;
@using System.Text.Encodings.Web;

@model BookmarkModel

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group mb-3">
        <label asp-for="Url" class="col-form-label"></label>
        <input asp-for="Url" class="form-control" />
        <div class="form-text text-danger">@this.GetString(Html.ValidationMessageFor(x => x.Url))</div>
    </div>

    <div class="form-group mb-3">
        <label asp-for="Title" class="col-form-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group row mb-3">
        <div class="col-12">
            <label asp-for="Description" class="col-form-label mb-1"></label>
            <textarea asp-for="Description" id="id-bookmark-editor" rows="6" class="form-control"></textarea>
        </div>
        <div class="form-group row">
            <hr />
            <div class="col-12">
                <input type="submit" value="Update" class="btn btn-primary" />
                <a asp-controller="Bookmark" asp-action="Index" class="btn btn-secondary">Go&nbsp;Back</a>
            </div>
        </div>
    </div>
</form>

@section Styles {
    <link rel="stylesheet" href="~/lib/easymde/dist/easymde.min.css" asp-append-version="true" />
}

@section Scripts {
    <script src="~/lib/easymde/dist/easymde.min.js"></script>
    <script>
        const easyMDE = new EasyMDE({ element: $('#id-bookmark-editor')[0] });
    </script>
}

@functions {
    IHtmlContent GetString(IHtmlContent content)
    {
        using (var writer = new StringWriter())
        {
            content.WriteTo(writer, HtmlEncoder.Default);
            return Html.Raw(HttpUtility.HtmlDecode(writer.ToString()));
        }
    }
}

Bookmarks/Views/Bookmark/Groups.cshtml
@model             GroupModel

@{
    ViewData["Title"] = "AddGroup";
    var mode = this.Model.Id == Guid.Empty ? "Add" : "Update";
}

<h1>Bookmark Groups</h1>

<hr />
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                Groups
            </div>
            <div class="card-body">
                <div class="dropdown">
                    <ul class="dropdown-menu">
                        @if (this.Model.Groups?.Any() ?? false)
                        {
                            foreach (var item in this.Model.Groups)
                            {
                                <li><a class="dropdown-item" href="/bookmark/groups/@item.Id">@item.Name</a></li>
                            }
                        }
                        else
                        {
                            <li>
                                No groups defines so far
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="card-footer">
                Bookmarks: @(this.Model.Bookmarks?.Count() ?? 0)
            </div>
        </div>
    </div>
    <div class="col-9">
        <form asp-action="Groups">
            <input name="bookmarkId" type="hidden" value=@this.TempData["bookmarkId"] />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <input asp-for="Name" class="form-control" placeholder="@nameof(GroupModel.Name)" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" id="id-group-editor" rows="4" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 float-end">
                @if (this.Model.Bookmarks?.Count() == 0)
                {
                    <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#confirmDeleteleModal">Delete</a>
                }

                @if (this.IsUpdating(this.Model))
                {
                    <a class="btn btn-primary" href="/bookmark/groups/">Clear</a>
                }

                <input type="submit" value="@mode" class="btn btn-primary" />
                <a asp-asp-controller="Bookmark" asp-action="Index" type="button" class="btn btn-secondary">Go&nbsp;Back</a>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="confirmDeleteleModal" tabindex="-1" aria-labelledby="confirmDeleteleModalLabel" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h5 class="modal-title" id="confirmDeleteleModalLabel">Please, confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete '@this.Model.Name' group? The operation is irevertible.
            </div>
            <div class="modal-footer">
                <button type="button" id="btn-delete" class="btn btn-danger" data-bs-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Styles
    {
    <link rel="stylesheet" href="~/lib/easymde/dist/easymde.min.css" asp-append-version="true" />
    <style>
        td {
            border: none;
        }

        .card-header {
            padding-bottom: .25rem;
        }

        .card-footer {
            padding-top: .25rem;
        }

        .dropdown-menu {
            position: static;
            display: block !important;
            padding: inherit;
        }

        .dropdown ul {
            border: none;
        }

        .dropdown .dropdown-item {
            padding: 0;
        }
    </style>
}

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/lib/easymde/dist/easymde.min.js"></script>
    <script>
        const easyMDE = new EasyMDE({ element: document.getElementById('id-group-editor') });
        $('#btn-delete').on('click', function () {
            $.post('/bookmark/deletegroup/@this.Model.Id', function () {
                window.location.href = '/bookmark/groups/';
            });
        });
    </script>
}

@functions {
    bool IsUpdating(GroupModel model)
    {
        return model.Id != Guid.Empty;
    }
}