ToDo/Models/ErrorViewModel.cs
namespace ToDos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo/Models/ToDoIndexModel.cs
using OpenCqs;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

using ToDos.UseCases.Queries;

namespace ToDos.Models
{
    public class ToDoListModel
    {
        private IQueryHandler<GetToDosQuery, IEnumerable<ToDoModel>> getTodos;

        public ToDoFilter Filter { get; init; }

        public ToDoListModel()
        {
        }

        public ToDoListModel(IQueryHandler<GetToDosQuery, IEnumerable<ToDoModel>> getTodos, string email, ToDoFilter filter = default)
        {
            this.getTodos = getTodos;
            this.EMail = email;
            this.Filter = filter;
        }

        public bool IsValid => this.getTodos != default;

        public string Text { get; set; }

        public string EMail { get; set; }   // maybe overwritten in each reminder

        public ToDoModel[] GetToDos(string userId)
        {
            var todosQuery = new GetToDosQuery(userId);// { EMail = this.EMail, Group = this.Filter?.Group, Search = this.Filter?.Search };
            return this.getTodos?.Handle(todosQuery).ToArray() ?? Array.Empty<ToDoModel>();
        }

        public class ToDoFilter
        {
            public ToDoFilter(string group, string search)
            {
                this.Group = group;
                this.Search = search;
            }

            public string Search { get; init; }

            public string Group { get; init; }
        }
    }
}

ToDo/Models/ToDoModel.cs
using System;

namespace ToDos.Models
{
    public class ToDoModel
    {
        public Guid Id { get; set; }
        
        public string UserId { get; set; }

        public string Text { get; set; }

        public bool Done { get; set; }

        public DateTime DueDateTime { get; set; }

        public string EMail { get; set; }

        public TimeUnit TimeUnit { get; set; }

        public ushort Remind { get; set; }

        public ushort Repeat { get; set; }

        public ushort Notified { get; set; }

        public bool Overdue { get; set; }
    }

    public enum TimeUnit
    {
        None, Minutes, Hours, Days
    }

    //public enum ToDoStatus
    //{
    //    Indeterminate, InProgress, Complete, Pending, Overdue
    //}
}

ToDo/Models/Validators/NoteListModelValidator.cs
using FluentValidation;

using ToDos.Models;

namespace Bookmarks.Models.Validators
{
    public class NoteListModelValidator : AbstractValidator<ToDoListModel>
    {
        public NoteListModelValidator()
        {
            this.RuleFor(x => x.Text).NotNull().WithMessage("ToDo text is required.");
        }
    }
}

ToDo/Models/Validators/ToDoModelValidator.cs
using FluentValidation;

using System;

namespace ToDos.Models.Validators
{
    public class ToDoModelValidator : AbstractValidator<ToDoModel>
    {
        public ToDoModelValidator()
        {
            const string textErrorMessage = "Todo's text must not be empty.";
            const string emailErrorMessage = "A valid email is required.";
            this.RuleFor(x => x.Text).NotNull().WithMessage(textErrorMessage).NotEmpty().WithMessage(textErrorMessage);
            this.RuleFor(x => x.DueDateTime).GreaterThanOrEqualTo(DateTime.Now);
            this.RuleFor(x => x.EMail)
                .NotNull().WithMessage(emailErrorMessage)
                .NotEmpty().WithMessage(emailErrorMessage)
                .When(x => x.Remind > 0)
                .When(x => x.TimeUnit != TimeUnit.None);
        }
    }
}

ToDo/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using OpenCqs;

using System;
using System.Collections.Generic;
using System.Security.Claims;

using ToDos.Code;
using ToDos.Data.Handlers;
using ToDos.Models;
using ToDos.UseCases.Commands;
using ToDos.UseCases.Queries;

namespace ToDos.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private readonly IQueryHandler<GetToDosQuery, IEnumerable<ToDoModel>> getToDos;
        private readonly ICommandHandler<AddToDoCommand, CommandResult> addToDo;
        //private const string Email = "achristov@hotmail.com";
        readonly IQueryHandler<GetToDoQuery, ToDoModel> getToDo;
        readonly ICommandHandler<UpdateToDoCommand, CommandResult> updateToDo;
        readonly ICommandHandler<SetToDoCheckedComplete, CommandResult> setToDoChecked;
        readonly ICommandHandler<DeleteToDoCommand, CommandResult> deleteToDo;
        readonly ToDoNotifier toDoNotifier;

        public ToDoController(IQueryHandler<GetToDosQuery, IEnumerable<ToDoModel>> getToDos
            , IQueryHandler<GetToDoQuery, ToDoModel> getToDo
            , ICommandHandler<AddToDoCommand, CommandResult> addToDo
            , ICommandHandler<UpdateToDoCommand, CommandResult> updateToDo
            , ICommandHandler<SetToDoCheckedComplete, CommandResult> setToDoChecked
            , ICommandHandler<DeleteToDoCommand, CommandResult> deleteToDo
            , ToDoNotifier toDoNotifier)
        {
            this.toDoNotifier = toDoNotifier ?? throw new ArgumentNullException(nameof(toDoNotifier), $"{nameof(toDoNotifier)} is null.");
            this.deleteToDo = deleteToDo ?? throw new ArgumentNullException(nameof(deleteToDo), $"{nameof(deleteToDo)} is null.");
            this.setToDoChecked = setToDoChecked ?? throw new ArgumentNullException(nameof(setToDoChecked), $"{nameof(setToDoChecked)} is null.");
            this.updateToDo = updateToDo ?? throw new ArgumentNullException(nameof(updateToDo), $"{nameof(updateToDo)} is null.");
            this.getToDos = getToDos ?? throw new ArgumentNullException(nameof(getToDos), $"{nameof(getToDos)} is null.");
            this.getToDo = getToDo ?? throw new ArgumentNullException(nameof(getToDo), $"{nameof(getToDo)} is null.");
            this.addToDo = addToDo ?? throw new ArgumentNullException(nameof(addToDo), $"{nameof(addToDo)} is null.");
        }

        public IActionResult Index()
        {
            var email = this.User?.FindFirstValue(ClaimTypes.Email) ?? string.Empty;
            var model = new ToDoListModel(this.getToDos, email);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(ToDoListModel model)
        {
            var email = this.User?.FindFirstValue(ClaimTypes.Email) ?? string.Empty;
            if (this.ModelState.IsValid)
            {
                var userId = this.User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
                var result = this.addToDo.Handle(new AddToDoCommand(model.Text, userId, email));
                if (result.IsSuccess)
                {
                    return this.RedirectToAction(nameof(Index));
                }
            }

            return this.View(new ToDoListModel(this.getToDos, email));
        }

        public IActionResult Edit(Guid id)
        {
            var email = this.User?.FindFirstValue(ClaimTypes.Email) ?? string.Empty;
            var model = this.getToDo.Handle(new GetToDoQuery(id, email));
            return this.View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoModel model)
        {
            if (this.ModelState.IsValid)
            {
                var result = this.updateToDo.Handle(new UpdateToDoCommand(model.Id
                    , model.Text
                    , model.Done
                    , model.DueDateTime
                    , model.EMail
                    , model.Remind
                    , model.TimeUnit
                    , model.Repeat));
                if (result.IsSuccess)
                {
                    this.toDoNotifier.HasNew = true;
                    return this.RedirectToAction(nameof(Index));
                }
            }

            return this.View(model);
        }

        [HttpPost/*, ValidateAntiForgeryToken*/]
        public IActionResult Check(Guid id, bool @checked)
        {
            this.setToDoChecked.Handle(new SetToDoCheckedComplete(id, @checked));
            return this.Ok();
        }

        [HttpPost/*, ValidateAntiForgeryToken*/]
        public IActionResult Delete(Guid id)
        {
            this.deleteToDo.Handle(new DeleteToDoCommand(id));
            return this.Ok();
        }
    }
}

ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDo/Views/ToDo/Edit.cshtml
@using ToDos.Code;
@using Microsoft.AspNetCore.Html;
@model ToDos.Models.ToDoModel

<form asp-action="Edit" class="container">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input id="time-unit" type="hidden" asp-for="TimeUnit" />
    <input type="hidden" asp-for="Id" />

    <div class="form-group row mb-3">
        <label asp-for="DueDateTime" class="col-form-label col-md-2">To Do:</label>
        <div class="col-md-10">
            <input type="text" class="form-control" readonly asp-for="Text" />
        </div>
    </div>

    <div class="form-group row mb-3">
        <label asp-for="DueDateTime" class="col-form-label col-md-2">Due Date &amp; Time:</label>
        <div class="col-md-10">
            <input asp-for="DueDateTime" class="form-control" asp-format="{0:yyyy-MM-ddTHH:mm}" value="@this.GetDueDateAndTime(this.Model)" />
            <span asp-validation-for="DueDateTime" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-3">
        <label asp-for="EMail" class="col-form-label col-md-2">Send a reminder to:</label>
        <div class="col-md-10">
            <input asp-for="EMail" class="form-control col-md-10" placeholder="EMail address" />
            <span asp-validation-for="EMail" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mb-3">
        <div class="col-md-1 col-md-sm-3 col-md-xs-4 offset-md-2">
            <input asp-for="Remind" class="form-control text-end me-1" />
            <span asp-validation-for="Remind" class="text-danger"></span>
        </div>

        <div class="col-md-3">
            <div class="dropdown">
                <button id="dropdownTimeUnit" type="button" class="btn btn-outline-secondary dropdown-toggle ps-3" style="vertical-align:unset" data-bs-toggle="dropdown" data-bs-todo-id="@this.Model.Id" aria-expanded="false">
                    @{
                        <text>@(this.Model.TimeUnit == TimeUnit.None ? "Select" : this.Model.TimeUnit)</text>
                    }
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownTimeUnit">
                    @{
                        foreach (var unit in this.GetTimeUnitNames())
                        {
                            <li><a class="dropdown-item" href="#">@unit</a></li>
                        }
                    }
                </ul>
                <label class="col-form-label ps-1">before.</label>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-form-label col-md-2">Then repeat it every: </label>
        <div class="col-md-1">
            <input asp-for="Repeat" class="form-control text-end" />
        </div>
        <label id="label-time-units" class="col-form-label col-md-7 ms-1"></label>
    </div>
    <div class="form-group row mb-3">
        <div class="col-md-10 offset-2">
            <span asp-validation-for="Repeat" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <hr />
        <div class="col-md-10 offset-md-2">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a asp-controller="ToDo" asp-action="Index" class="btn btn-secondary">Go&nbsp;Back</a>
        </div>
    </div>
</form>

@section Styles {
    <style>
        .dropdown button {
            padding-top: 6px;
            padding-bottom: 6px;
        }
    </style>
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $('a.dropdown-item').on('click', function (e) {
            e.preventDefault();
            var units = $(this).text();
            var parent = $(this).closest('div.dropdown');
            $('.dropdown-toggle', parent).text(units);
            $('#label-time-units').text(units);
            $('input#time-unit').val(units);
        });

        $('input#time-unit').on('change', function (e) {
            e.preventDefault();
            alert('changed!');
        });
    </script>
}

@functions {
    IEnumerable<string> GetTimeUnitNames()
    {
        return Enum.GetNames(typeof(TimeUnit)).Skip(1);
    }

    IHtmlContent GetDueDateAndTime(ToDoModel model)
    {
        var result = (model.DueDateTime == DateTime.MinValue ? DateTime.Now : model.DueDateTime).NoSeconds();
        return new HtmlString(result.ToString("s"));
    }
}

ToDo/Views/ToDo/Index.cshtml
@using System.Security.Claims;
@using ToDos.Code;
@using Microsoft.AspNetCore.Html;
@using System.Text;
@model ToDoListModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">To Do's</h1>
    <p>&mdash;&nbsp;Never loose what you want to do again&nbsp;&mdash;</p>
</div>

<form asp-action="Index">
    <div class="form-group row mb-3">
        <div class="col-11">
            <input asp-for="Text" class="form-control" placeholder="Enter todo's text" />
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <div class="col-1">
            <div class="d-grid">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<table class="table table-borderless table-sm">
    <thead>
        <tr>
            <th scope="col" class="em-4">Actions</th>
            <th scope="col">To Do</th>
            <th scope="col" class="em-4">Status</th>
        </tr>
    </thead>
    <tbody>
        @{
            var userId = this.User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
            var todos = this.Model.GetToDos(userId);
            for (var index = 0; index < todos.Count(); index++)
            {
                var item = todos[index];
                var isOverdue = item.DueDateTime != DateTime.MinValue && item.DueDateTime < DateTime.Now.NoSeconds() && !item.Done;
                var overdue = isOverdue ? "text-danger" : string.Empty;
                <tr>
                    <td class="text-center">
                        <a href="#" title="View details" class="text-center" data-bs-toggle="collapse" data-bs-target="#collapse-@index" aria-expanded="false" aria-controls="collapse-@index">
                            <i class="bi bi-arrow-clockwise"></i>
                        </a>
                    </td>
                    <td>
                        <span class="truncate @overdue">
                            @item.Text
                        </span>
                    </td>
                    <td>

                        <div class="form-check" style="display: flex; justify-content: center">
                            <input class="form-check-input" asp-for="@item.Done" data-item-id="@item.Id">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="3" class="p-0">
                        <div class="collapse" id="collapse-@index">
                            @if (item.DueDateTime == default)
                            {
                                <div class="card">
                                    <div class="card-body mt-3">
                                        No due date and time set.
                                    </div>
                                    <div class="card-footer">
                                        <a class="btn btn-primary" href="/ToDo/Edit/@item.Id">Deadline</a>
                                        <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#confirmDeleteleModal" data-item-id="@item.Id">Delete</a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="card">
                                    <div class="card-body mt-3">
                                        @this.DeadlineAndReminderText(item)
                                    </div>
                                    <div class="card-footer">
                                        <a class="btn btn-primary" href="/ToDo/Edit/@item.Id">Modify</a>
                                        <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#confirmDeleteleModal" data-item-id="@item.Id">Delete</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="modal fade" id="confirmDeleteleModal" tabindex="-1" aria-labelledby="confirmDeleteleModalLabel" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h5 class="modal-title" id="confirmDeleteleModalLabel">Please, confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete this item? The operation is irevertible.
            </div>
            <div class="modal-footer">
                <button type="button" id="btn-delete" class="btn btn-danger" data-bs-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <style>
        .card-body {
            margin-top: 0;
            margin-bottom: 0;
            padding-top: 0;
        }

        form#deadline-form .input-group {
            align-items: center;
        }

        .accordion-body {
            padding-right: 1px;
        }

    </style>
}

@section Scripts {
    <script>
        $('#confirmDeleteleModal').on('show.bs.modal', function (e) {
            var button = e.relatedTarget;
            var id = $(button).attr('data-item-id');
            $('#btn-delete', this).attr('data-item-id', id);
        });

        $('td a').on('click', function () {
            $('i', this).toggleClass('bi-arrow-counterclockwise');
            $('i', this).toggleClass('bi-arrow-clockwise');
        });

        $('#btn-delete').on('click', function () {
            var id = $(this).attr('data-item-id');
            $.post('/todo/delete/' + id, function () {
                window.location.href = '/todo/index';
            });
        });

        $('input[type="checkbox"]').on('change', function(e) {
            e.preventDefault();
            var id = $(this).attr('data-item-id');
            $.post('/todo/check/' + id, { checked: this.checked }, function () {
                window.location.href = '/todo/index';
            });
        });
    </script>
}

@functions {
    IHtmlContent GetTimeUnit(TimeUnit timeUnit, uint before)
    {
        var name = Enum.GetName(typeof(TimeUnit), timeUnit).ToLower();
        return new HtmlString(before == 1 ? name : name[..(name.Length - 1)]);
    }

    IHtmlContent DeadlineAndReminderText(ToDoModel item)
    {
        var mhd = $"{item.TimeUnit}".ToLower();
        var builder = new StringBuilder($"Deadline set to <strong>{item.DueDateTime}</strong>. ");

        var now = DateTime.Now.NoSeconds();
        var remind = now;
        switch (item.TimeUnit)
        {
            case TimeUnit.Days:
                remind.AddDays(-item.Remind);
                break;

            case TimeUnit.Hours:
                remind.AddHours(-item.Remind);
                break;

            case TimeUnit.Minutes:
                remind.AddMinutes(-item.Remind);
                break;

            default:    
                remind.AddMinutes(-5);  // default time before deadline when no reminder set
                break;
        }

        if (item.DueDateTime >= remind && item.DueDateTime <= now && !item.Done)
        {
            if (item.Remind != 0)
            {
                builder.Append($"A reminder will be sent to '{item.EMail}' {item.Remind} {mhd} before the deadline is reached. ");
            }

            var diff = remind - item.DueDateTime;
            var days = diff.Days;
            var hours = diff.Hours;
            var minutes = diff.Minutes;

            var daysText = days != 1 ? "days" : "day";
            var hoursText = hours != 1 ? "hours" : "hour";
            var minutesText = minutes != 1 ? "minutes" : "minute";

            var overdue = string.Empty;
            if (days != 0)
            {
                overdue = $"{days} {daysText}, {hours} {hoursText}, {minutes} {minutesText}";
            }
            else if (hours != 0)
            {
                overdue = $"{hours} {hoursText}, {minutes} {minutesText}";
            }
            else
            {
                overdue = $"{minutes} {minutesText}";
            }

            builder.Append($"Overdue {overdue}.");
        }
        
        if (item.Done)
        {
            builder.Append($" Done!");
        }

        if (item.Notified != 0)
        {
            builder.Append($" Recipient has been notified {item.Notified} time(s).");
        }

        var text = builder.ToString();

        return new HtmlString(text);
    }

}