Notes/Models/ErrorViewModel.cs
namespace Notes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Notes/Models/NoteListModel.cs
using Notes.UseCases.Queries;

using OpenCqs;

using System;
using System.Collections.Generic;
using System.Linq;

namespace Notes.Models
{
    public class NoteListModel
    {
        private readonly IQueryHandler<GetNotesQuery, IEnumerable<NoteModel>> getNotes;

        public NoteListModel()
        {
        }

        public NoteListModel(IQueryHandler<GetNotesQuery, IEnumerable<NoteModel>> getNotes, NotesFilter filter = default)
        {
            this.Filter = filter;
            this.getNotes = getNotes;
        }

        public string Title { get; set; }

        public string Content { get; set; }

        public NotesFilter Filter { get; }

        public NoteModel[] GetNotes()
        {
            var notesQuery = new GetNotesQuery { Group = this.Filter?.Group, Search = this.Filter?.Search };
            return this.getNotes?.Handle(notesQuery).ToArray() ?? Array.Empty<NoteModel>();
        }

        public class NotesFilter
        {
            public string Group { get; internal set; }

            public string Search { get; internal set; }
        }
    }

    public class NoteModel
    {
        public Guid Id { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }
    }
}

Notes/Models/Validators/NoteListModelValidator.cs
using FluentValidation;

using Notes.Models;

namespace Bookmarks.Models.Validators
{
    public class NoteListModelValidator : AbstractValidator<NoteListModel>
    {
        public NoteListModelValidator()
        {
            this.RuleFor(x => x.Title).NotNull().WithMessage("Note title is required.");
        }
    }
}

Notes/Controllers/NoteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Notes.Data.Handlers;
using Notes.Models;
using Notes.UseCases.Commands;
using Notes.UseCases.Queries;

using OpenCqs;

using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace Notes.Controllers
{
    [Authorize]
    public class NoteController : Controller
    {
        private readonly IQueryHandler<GetNotesQuery, IEnumerable<NoteModel>> getNotes;
        private readonly IQueryHandler<GetNoteQuery, NoteModel> getNote;
        private readonly ICommandHandler<AddNoteCommand, CommandResult> addNote;
        private readonly ICommandHandler<UpdateNoteCommand, CommandResult> updateNote;
        private readonly ICommandHandler<DeleteNoteCommand, CommandResult> deleteNote;

        public NoteController(IQueryHandler<GetNotesQuery, IEnumerable<NoteModel>> getNotes
            , IQueryHandler<GetNoteQuery, NoteModel> getNote
            , ICommandHandler<AddNoteCommand, CommandResult> addNote
            , ICommandHandler<UpdateNoteCommand, CommandResult> updateNote
            , ICommandHandler<DeleteNoteCommand, CommandResult> deleteNote)
        {
            this.getNotes = getNotes ?? throw new ArgumentNullException(nameof(getNotes), $"{nameof(getNotes)} is null.");
            this.getNote = getNote ?? throw new ArgumentNullException(nameof(getNote), $"{nameof(getNote)} is null.");
            this.deleteNote = deleteNote ?? throw new ArgumentNullException(nameof(deleteNote), $"{nameof(deleteNote)} is null.");
            this.updateNote = updateNote ?? throw new ArgumentNullException(nameof(updateNote), $"{nameof(updateNote)} is null.");
            this.addNote = addNote ?? throw new ArgumentNullException(nameof(addNote), $"{nameof(addNote)} is null.");
        }

        public IActionResult Index()
        {
            var model = new NoteListModel(this.getNotes);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(NoteListModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
                var result = this.addNote.Handle(new AddNoteCommand(model.Title, model.Content, userId));
                if (result.IsSuccess)
                {
                    return this.RedirectToAction(nameof(Index));
                }
            }

            return this.View(new NoteListModel(this.getNotes));
        }

        public IActionResult Edit(Guid id)
        {
            var model = this.getNote.Handle(new GetNoteQuery(id));
            return this.View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(NoteModel model)
        {
            if (this.ModelState.IsValid)
            {
                var result = this.updateNote.Handle(new UpdateNoteCommand(model.Id, model.Title, model.Content));
                if (result.IsSuccess)
                {
                    return this.View();
                }
            }

            return this.View(model);
        }

        [HttpPost/*, ValidateAntiForgeryToken*/]
        public IActionResult Delete(Guid id)
        {
            this.deleteNote.Handle(new DeleteNoteCommand(id));
            return this.Ok();
        }
    }
}

Notes/Views/Note/Edit.cshtml
@model             NoteModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Note</h1>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group mb-3">
        <label asp-for="Title" class="col-form-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group row mb-3">
        <div class="col-12">
            <label asp-for="Content" class="col-form-label mb-1"></label>
            <textarea asp-for="Content" id="id-note-editor" rows="6" class="form-control"></textarea>
        </div>

        <div class="form-group row">
            <div class="col-12">
                <input type="submit" value="Update" class="btn btn-primary" />
                <a asp-controller="Note" asp-action="Index" class="btn btn-secondary">Go&nbsp;Back</a>
            </div>
        </div>
    </div>
</form>

@section Styles {
    <link rel="stylesheet" href="~/lib/easymde/dist/easymde.min.css" asp-append-version="true" />
}

@section Scripts {
    <script src="~/lib/easymde/dist/easymde.min.js"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        const easyMDE = new EasyMDE({ element: $('#id-note-editor')[0] });
    </script>
}

Notes/Views/Note/Index.cshtml
@model NoteListModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Notes</h1>
    <p>&mdash;&nbsp;Never loose your notes again&nbsp;&mdash;</p>
</div>

<form asp-action="Index">
    <div class="form-group row mb-3">
        <div class="col-11">
            <input asp-for="Title" class="form-control" placeholder="Enter the title of the new note" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="col-1">
            <div class="d-grid">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<table class="table table-borderless table-sm">
    <thead>
        <tr>
            <th scope="col" class="em-2">#</th>
            <th scope="col" class="em-6 text-center">Details</th>
            <th scope="col">Title</th>
        </tr>
    </thead>
    <tbody>
        @{
            var notes = this.Model.GetNotes();
            for (var index = 0; index < notes.Count(); index++)
            {
                var item = notes[index];
                <tr>
                    <td scope="row">@(index + 1).</td>
                    <td class="text-center">
                        <a href="#" title="View details" class="text-center" data-bs-toggle="collapse" data-bs-target="#collapse-@index" aria-expanded="false" aria-controls="collapse-@index">
                            <i class="bi bi-arrow-clockwise"></i>
                        </a>
                    </td>
                    <td>
                        <span class="truncate">
                            @item.Title
                        </span>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="p-0">
                        <div class="collapse" id="collapse-@index">
                            <div class="card ml-4 p-2">
                                <div class="card-body">
                                    @Html.Raw(item.Content ?? "No content")
                                </div>
                                <div class="card-footer">
                                    <a title="Edit" class="btn btn-primary" href="/Note/Edit/@item.Id">Modify</a>
                                    <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#confirmDeleteleModal" data-item-id="@item.Id">Delete</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="modal fade" id="confirmDeleteleModal" tabindex="-1" aria-labelledby="confirmDeleteleModalLabel" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-danger">
                <h5 class="modal-title" id="confirmDeleteleModalLabel">Please, confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you want to delete this note? The operation is irevertible.
            </div>
            <div class="modal-footer">
                <button type="button" id="btn-delete" class="btn btn-danger" data-bs-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#confirmDeleteleModal').on('show.bs.modal', function (e) {
            var button = e.relatedTarget;
            var id = $(button).attr('data-item-id');
            $('#btn-delete', this).attr('data-item-id', id);
        });

        $('td a').on('click', function () {
            $('i', this).toggleClass('bi-arrow-counterclockwise');
            $('i', this).toggleClass('bi-arrow-clockwise');
        });

        $('#btn-delete').on('click', function () {
            var id = $(this).attr('data-item-id');
            $.post('/note/delete/' + id, function () {
                window.location.href = '/note/index';
            });
        });
    </script>
}